module TestWalls where

import Walls

testWalls :: [Wall]
testWalls =
  [ Wall {wallTile = (0,0), wallOrientation = Horizontal}
  , Wall {wallTile = (0,0), wallOrientation = Vertical}
  , Wall {wallTile = (0,1), wallOrientation = Horizontal}
  , Wall {wallTile = (0,2), wallOrientation = Vertical}
  , Wall {wallTile = (0,4), wallOrientation = Horizontal}
  , Wall {wallTile = (0,4), wallOrientation = Vertical}
  , Wall {wallTile = (0,6), wallOrientation = Horizontal}
  , Wall {wallTile = (0,6), wallOrientation = Vertical}
  , Wall {wallTile = (0,7), wallOrientation = Horizontal}
  , Wall {wallTile = (0,8), wallOrientation = Horizontal}
  , Wall {wallTile = (0,8), wallOrientation = Vertical}
  , Wall {wallTile = (1,1), wallOrientation = Vertical}
  , Wall {wallTile = (1,2), wallOrientation = Horizontal}
  , Wall {wallTile = (1,3), wallOrientation = Horizontal}
  , Wall {wallTile = (1,3), wallOrientation = Vertical}
  , Wall {wallTile = (1,5), wallOrientation = Horizontal}
  , Wall {wallTile = (1,5), wallOrientation = Vertical}
  , Wall {wallTile = (1,7), wallOrientation = Vertical}
  , Wall {wallTile = (1,9), wallOrientation = Horizontal}
  , Wall {wallTile = (1,9), wallOrientation = Vertical}
  , Wall {wallTile = (2,0), wallOrientation = Horizontal}
  , Wall {wallTile = (2,1), wallOrientation = Horizontal}
  , Wall {wallTile = (2,1), wallOrientation = Vertical}
  , Wall {wallTile = (2,3), wallOrientation = Vertical}
  , Wall {wallTile = (2,4), wallOrientation = Horizontal}
  , Wall {wallTile = (2,5), wallOrientation = Vertical}
  , Wall {wallTile = (2,6), wallOrientation = Horizontal}
  , Wall {wallTile = (2,7), wallOrientation = Horizontal}
  , Wall {wallTile = (2,7), wallOrientation = Vertical}
  , Wall {wallTile = (2,8), wallOrientation = Horizontal}
  , Wall {wallTile = (2,9), wallOrientation = Vertical}
  , Wall {wallTile = (3,1), wallOrientation = Vertical}
  , Wall {wallTile = (3,2), wallOrientation = Horizontal}
  , Wall {wallTile = (3,3), wallOrientation = Horizontal}
  , Wall {wallTile = (3,3), wallOrientation = Vertical}
  , Wall {wallTile = (3,5), wallOrientation = Horizontal}
  , Wall {wallTile = (3,5), wallOrientation = Vertical}
  , Wall {wallTile = (3,7), wallOrientation = Vertical}
  , Wall {wallTile = (3,9), wallOrientation = Horizontal}
  , Wall {wallTile = (3,9), wallOrientation = Vertical}
  , Wall {wallTile = (4,0), wallOrientation = Horizontal}
  , Wall {wallTile = (4,0), wallOrientation = Vertical}
  , Wall {wallTile = (4,1), wallOrientation = Horizontal}
  , Wall {wallTile = (4,2), wallOrientation = Vertical}
  , Wall {wallTile = (4,4), wallOrientation = Horizontal}
  , Wall {wallTile = (4,4), wallOrientation = Vertical}
  , Wall {wallTile = (4,6), wallOrientation = Horizontal}
  , Wall {wallTile = (4,6), wallOrientation = Vertical}
  , Wall {wallTile = (4,7), wallOrientation = Horizontal}
  , Wall {wallTile = (4,8), wallOrientation = Horizontal}
  , Wall {wallTile = (4,8), wallOrientation = Vertical}
  , Wall {wallTile = (5,0), wallOrientation = Vertical}
  , Wall {wallTile = (5,2), wallOrientation = Horizontal}
  , Wall {wallTile = (5,2), wallOrientation = Vertical}
  , Wall {wallTile = (5,3), wallOrientation = Horizontal}
  , Wall {wallTile = (5,4), wallOrientation = Vertical}
  , Wall {wallTile = (5,5), wallOrientation = Horizontal}
  , Wall {wallTile = (5,6), wallOrientation = Vertical}
  , Wall {wallTile = (5,8), wallOrientation = Vertical}
  , Wall {wallTile = (5,9), wallOrientation = Horizontal}
  , Wall {wallTile = (6,0), wallOrientation = Horizontal}
  , Wall {wallTile = (6,1), wallOrientation = Horizontal}
  , Wall {wallTile = (6,1), wallOrientation = Vertical}
  , Wall {wallTile = (6,3), wallOrientation = Vertical}
  , Wall {wallTile = (6,4), wallOrientation = Horizontal}
  , Wall {wallTile = (6,5), wallOrientation = Vertical}
  , Wall {wallTile = (6,6), wallOrientation = Horizontal}
  , Wall {wallTile = (6,7), wallOrientation = Horizontal}
  , Wall {wallTile = (6,7), wallOrientation = Vertical}
  , Wall {wallTile = (6,8), wallOrientation = Horizontal}
  , Wall {wallTile = (6,9), wallOrientation = Vertical}
  , Wall {wallTile = (7,1), wallOrientation = Vertical}
  , Wall {wallTile = (7,2), wallOrientation = Horizontal}
  , Wall {wallTile = (7,3), wallOrientation = Horizontal}
  , Wall {wallTile = (7,3), wallOrientation = Vertical}
  , Wall {wallTile = (7,5), wallOrientation = Horizontal}
  , Wall {wallTile = (7,5), wallOrientation = Vertical}
  , Wall {wallTile = (7,7), wallOrientation = Vertical}
  , Wall {wallTile = (7,9), wallOrientation = Horizontal}
  , Wall {wallTile = (7,9), wallOrientation = Vertical}
  , Wall {wallTile = (8,0), wallOrientation = Horizontal}
  , Wall {wallTile = (8,1), wallOrientation = Horizontal}
  , Wall {wallTile = (8,1), wallOrientation = Vertical}
  , Wall {wallTile = (8,3), wallOrientation = Vertical}
  , Wall {wallTile = (8,4), wallOrientation = Horizontal}
  , Wall {wallTile = (8,5), wallOrientation = Vertical}
  , Wall {wallTile = (8,6), wallOrientation = Horizontal}
  , Wall {wallTile = (8,7), wallOrientation = Horizontal}
  , Wall {wallTile = (8,7), wallOrientation = Vertical}
  , Wall {wallTile = (8,8), wallOrientation = Horizontal}
  , Wall {wallTile = (8,9), wallOrientation = Vertical}
  , Wall {wallTile = (9,1), wallOrientation = Vertical}
  , Wall {wallTile = (9,2), wallOrientation = Horizontal}
  , Wall {wallTile = (9,3), wallOrientation = Horizontal}
  , Wall {wallTile = (9,3), wallOrientation = Vertical}
  , Wall {wallTile = (9,5), wallOrientation = Horizontal}
  , Wall {wallTile = (9,5), wallOrientation = Vertical}
  , Wall {wallTile = (9,7), wallOrientation = Vertical}
  , Wall {wallTile = (9,9), wallOrientation = Horizontal}
  , Wall {wallTile = (9,9), wallOrientation = Vertical}
  ]